site_name: Diplomify - Academy

theme:
  name: material
  custom_dir: overrides
  favicon: img/assets/logo_medal.svg
  language: de
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.sections
    - navigation.footer
  font: false

copyright: 'Copyright &copy; 2023 Namaco UG (haftungsbeschränkt) <span class="mx-1">|</span> <a href="/imprint">Impressum</a> &middot; <a href="/privacy">Datenschutzerklärung</a>'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - meta
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.keys

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - search
  - tags

nav:
  - 'Startseite': 'index.md'

  #- 'Häufig gefragt': 'Anleitungen/FAQ/collection.md'

  - 'Schritt für Schritt Anleitungen':
      - 'Bewerten':
          - 'Noten eintragen': 'Anleitungen/Schritt_für_Schritt/Noten_eintragen.md'
          - 'Versetzungswarnungen': 'Anleitungen/Schritt_für_Schritt/Versetzungswarnungen.md'
      - 'Klassenübersicht':
          - 'Arbeits- & Sozialverhalten': 'Anleitungen/Schritt_für_Schritt/Arbeits-_&_Sozialverhalten.md'
          - 'Die Checkliste': 'Anleitungen/Arbeitsbereiche/checkliste.md'
          - 'Klassenleitung': 'Anleitungen/Schritt_für_Schritt/Klassenleitung.md'
          - 'Dienste zuweisen': 'Anleitungen/Schritt_für_Schritt/Dienste.md'
          - 'Fehltage': 'Anleitungen/Schritt_für_Schritt/Fehltage.md'
          - 'Kolleg*innen erinnern': 'Anleitungen/Schritt_für_Schritt/Kolleg*innen_erinnern.md'
          - 'Zeugniskonferenz': 'Anleitungen/Schritt_für_Schritt/Zeugniskonferenz.md'
          - 'Zeugnisdaten ändern': 'Anleitungen/Schritt_für_Schritt/Zeugnisdaten_ändern.md'
          - 'Zeugnisse erstellen': 'Anleitungen/Schritt_für_Schritt/Zeugnisse_erstellen.md'
          - 'Zeugnisse zum Druck freigeben': 'Anleitungen/Schritt_für_Schritt/Zeugnisse_zum_Druck_freigeben.md'
          - 'Zeugnisse zuordnen': 'Anleitungen/Schritt_für_Schritt/Zeugnisse_zuordnen.md'
          - 'Zeugnisvorschau': 'Anleitungen/Schritt_für_Schritt/Zeugnisvorschau.md'
      - 'Mein Unterricht':
          - 'Klassen & Kurse anlegen': 'Anleitungen/Schritt_für_Schritt/Klassen_und_Kurse_anlegen.md'
          - 'Unterricht zu "Mein Unterricht" hinzufügen': 'Anleitungen/Schritt_für_Schritt/mein_unterricht_hinzufügen.md'
      - 'Schüleransicht':
          - 'Förderbedarf eintragen': 'Anleitungen/Schritt_für_Schritt/Foerderbedarf_eintragen.md'
      - 'Einzefachansicht':
          - 'Unterricht & Kurse editieren': 'Anleitungen/Arbeitsbereiche/unterricht_editieren.md'



  - 'Administration':
      #- 'Admin-Startseite': 'Anleitungen/Administration/Übersicht.md'
      - 'Rechte vergeben': 'Anleitungen/Administration/Rechte_vergeben.md' 
      - 'Klassenleitungen festlegen': 'Anleitungen/Administration/klassenlehrerantrag.md'
      #- 'Grundlegende ToDos': 'Anleitungen/Administration/Inbetriebnahme.md'
      - 'Fächer & Fachgruppen verwalten': 'Anleitungen/Administration/Fächer_anlegen.md'
      - 'Schuljahre verwalten': 'Anleitungen/Administration/Schuljahre_verwalten.md'
      #- 'Import': 'Anleitungen/Administration/Import.md'
      - 'Schüler und Klassen verwalten': 'Anleitungen/Administration/Schüler_und_Klassen_verwalten.md'
      - 'Backups': 'Anleitungen/Administration/Backup.md'
      - 'Versetzungswarnungen': 'Anleitungen/Administration/Versetzungswarnungen_schulweit_drucken.md'
      - 'DaNis-Export': 'Anleitungen/Administration/Danisexport.md'
      - 'Integrationen': 'Anleitungen/Administration/Integrationen.md'
      - 'ILE-Dokumentationen': 'Anleitungen/Administration/ILE.md'
      - 'Zeugnisse bearbeiten': 'Anleitungen/Administration/Zeugnisse_bearbeiten.md'

  - 'Showroom':
      - 'Zeugnisse': 'showroom/zeugnisse.md'

  - 'Changelog':
      - 'Letzte Änderungen': 'Latest Changes/changes.md'