site_name: Diplomify - Academy

theme:
  name: material
  favicon: img/assets/logo_medal.svg
  language: de
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.sections
   
  font: false   

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - meta
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.keys

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - search
  - tags

nav:
  - 'Startseite': 'index.md'

  - 'Schritt für Schritt Anleitungen':
    - 'Bewerten':
      - 'Noten eintragen': 'Anleitungen/Schritt_für_Schritt/Noten_eintragen.md' 
    - 'Klassenübersicht':
      - 'Arbeits- & Sozialverhalten': 'Anleitungen/Schritt_für_Schritt/Arbeits-_&_Sozialverhalten.md'
      - 'Dich selbst als Klassenleitung eintragen': 'Anleitungen/Schritt_für_Schritt/Dich_selbst_als_Klassenleitung_eintragen.md'
      - 'Fehltage': 'Anleitungen/Schritt_für_Schritt/Fehltage.md'
      - 'Kolleg*innen erinnern': 'Anleitungen/Schritt_für_Schritt/Kolleg*innen_erinnern.md'
      - 'Zeugnisdaten ändern': 'Anleitungen/Schritt_für_Schritt/Zeugnisdaten_ändern.md'
      - 'Zeugnisse erstellen': 'Anleitungen/Schritt_für_Schritt/Zeugnisse_erstellen.md'
      - 'Zeugnisse zum Druck freigeben': 'Anleitungen/Schritt_für_Schritt/Zeugnisse_zum_Druck_freigeben.md'
      - 'Zeugnisse zuordnen': 'Anleitungen/Schritt_für_Schritt/Zeugnisse_zuordnen.md'
      - 'Zeugnisvorschau': 'Anleitungen/Schritt_für_Schritt/Zeugnisvorschau.md'
    - 'Mein Unterricht':
      - 'Klassen & Kurse anlegen': 'Anleitungen/Schritt_für_Schritt/Klassen_und_Kurse_anlegen.md'     
  


  - 'Administration':
    - 'Grundlegende ToDos': 'Anleitungen/Administration/Inbetriebnahme.md'
    - 'Admin-Startseite': 'Anleitungen/Administration/Übersicht.md'
    - 'Fächer & Fachgruppen verwalten': 'Anleitungen/Administration/Fächer_anlegen.md'
    - 'Schuljahre anlegen': 'Anleitungen/Administration/Schuljahre_anlegen.md'   
    - 'Termine anlegen': 'Anleitungen/Administration/Termine_anlegen.md' 
    - 'Import': 'Anleitungen/Administration/Import.md'    
    - 'Schüler und Klassen verwalten': 'Anleitungen/Administration/Schüler_und_Klassen_verwalten.md' 
    - 'Backups': 'Anleitungen/Administration/Backup.md' 
